# Generated by Django 5.0.7 on 2024-07-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='average_interaction_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='chatbot_interactions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='conversion_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
