# Generated by Django 5.0.7 on 2024-07-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_average_interaction_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='starting_pitch',
            field=models.TextField(blank=True),
        ),
    ]
